import { CharacterTag, CharacterWorldData } from './types';

export const CHARACTER_COMMON_TAGS: Record<
  'shot' | 'style' | 'light' | 'color',
  CharacterTag[]
> = {
  shot: [
    { zh: '全身', en: 'full body' },
    { zh: '半身', en: 'upper body' },
    { zh: '特寫', en: 'close-up' },
    { zh: '側臉', en: 'profile view' },
    { zh: '仰角', en: 'low angle' },
  ],
  style: [
    { zh: '寫實電影感', en: 'cinematic realistic style' },
    { zh: '日系動畫', en: 'japanese anime style' },
    { zh: '韓系網漫', en: 'korean webtoon style' },
    { zh: '現代扁平插畫', en: 'modern flat illustration style' },
    { zh: '水彩夢幻', en: 'soft watercolor dreamy style' },
  ],
  light: [
    { zh: '自然光', en: 'natural light' },
    { zh: '黃金時刻', en: 'golden hour lighting' },
    { zh: '霓虹光', en: 'neon lighting' },
    { zh: '背光', en: 'backlighting' },
    { zh: '棚燈', en: 'studio lighting' },
  ],
  color: [
    { zh: '高飽和', en: 'high saturation palette' },
    { zh: '莫蘭迪', en: 'morandi palette' },
    { zh: '黑白', en: 'monochrome palette' },
    { zh: '藍橘對比', en: 'teal and orange palette' },
    { zh: '柔和粉彩', en: 'pastel color palette' },
  ],
};

export const CHARACTER_WORLD_DATA: CharacterWorldData = {
  fantasy: {
    character: [
      { zh: '精靈弓手', en: 'elf archer' },
      { zh: '龍裔少女', en: 'dragonkin girl' },
      { zh: '符文法師', en: 'rune mage' },
      { zh: '聖騎士', en: 'paladin knight' },
      { zh: '九尾狐靈', en: 'nine-tailed fox spirit' },
    ],
    pose: [
      { zh: '施法中', en: 'casting a spell' },
      { zh: '拉弓瞄準', en: 'drawing a bow' },
      { zh: '持劍站姿', en: 'sword-ready stance' },
      { zh: '飄浮半空', en: 'floating in mid-air' },
      { zh: '祈禱', en: 'praying pose' },
    ],
    outfit: [
      { zh: '法袍', en: 'ornate mage robe' },
      { zh: '輕甲斗篷', en: 'light armor with cloak' },
      { zh: '旅行者皮裝', en: 'adventurer leather outfit' },
      { zh: '神官服', en: 'priestess attire' },
      { zh: '華麗晚禮服', en: 'fantasy evening gown' },
    ],
    env: [
      { zh: '魔法森林', en: 'enchanted forest' },
      { zh: '水晶洞穴', en: 'crystal cave' },
      { zh: '浮空城', en: 'floating citadel' },
      { zh: '古代遺跡', en: 'ancient ruins' },
      { zh: '月夜神殿', en: 'moonlit temple' },
    ],
    rare: [
      { zh: '發光符文', en: 'glowing runes' },
      { zh: '精靈耳', en: 'elf ears' },
      { zh: '龍角', en: 'dragon horns' },
      { zh: '漂浮水晶', en: 'floating crystals' },
      { zh: '星塵光暈', en: 'stardust aura' },
    ],
  },
  modern: {
    character: [
      { zh: '時尚模特', en: 'fashion model' },
      { zh: '街頭創作者', en: 'street creator' },
      { zh: '音樂人', en: 'indie musician' },
      { zh: '職場菁英', en: 'business professional' },
      { zh: '潮流攝影師', en: 'urban photographer' },
    ],
    pose: [
      { zh: '看手機', en: 'checking smartphone' },
      { zh: '回眸', en: 'looking back pose' },
      { zh: '走路抓拍', en: 'walking candid pose' },
      { zh: '靠牆站立', en: 'leaning on wall' },
      { zh: '自信交叉手', en: 'confident crossed-arms pose' },
    ],
    outfit: [
      { zh: '西裝套裝', en: 'tailored suit set' },
      { zh: 'Smart Casual', en: 'smart casual outfit' },
      { zh: '街頭潮服', en: 'streetwear fit' },
      { zh: '牛仔外套', en: 'denim jacket look' },
      { zh: '極簡黑白穿搭', en: 'minimal black-white styling' },
    ],
    env: [
      { zh: '城市街頭', en: 'city street scene' },
      { zh: '咖啡館', en: 'cozy coffee shop' },
      { zh: '攝影棚', en: 'studio backdrop' },
      { zh: '夜景天台', en: 'night rooftop' },
      { zh: '藝廊空間', en: 'modern art gallery' },
    ],
    rare: [
      { zh: '霓虹反光', en: 'neon reflections' },
      { zh: '膠片顆粒', en: 'film grain texture' },
      { zh: '雨夜水光', en: 'wet street reflections' },
      { zh: '光斑散景', en: 'bokeh highlights' },
      { zh: '雙重曝光感', en: 'double exposure feel' },
    ],
  },
  scifi: {
    character: [
      { zh: '機甲駕駛員', en: 'mecha pilot' },
      { zh: '星際遊俠', en: 'space ranger' },
      { zh: '賽博忍者', en: 'cyber ninja' },
      { zh: '仿生人', en: 'android operative' },
      { zh: '量子工程師', en: 'quantum engineer' },
    ],
    pose: [
      { zh: '啟動全息介面', en: 'activating holographic UI' },
      { zh: '戰術戒備', en: 'tactical ready stance' },
      { zh: '漂浮失重', en: 'zero-gravity floating pose' },
      { zh: '持能量刃', en: 'wielding energy blade' },
      { zh: '觀測遠方', en: 'scanning horizon' },
    ],
    outfit: [
      { zh: '戰術外骨骼', en: 'tactical exosuit' },
      { zh: '賽博裝甲', en: 'cyber armor suit' },
      { zh: '太空制服', en: 'space uniform' },
      { zh: '機能風長外套', en: 'techwear long coat' },
      { zh: '高科技頭盔', en: 'advanced combat helmet' },
    ],
    env: [
      { zh: '賽博都市', en: 'cyberpunk megacity' },
      { zh: '太空艙', en: 'spaceship interior' },
      { zh: '高科技實驗室', en: 'futuristic lab' },
      { zh: '霓虹巷道', en: 'neon alleyway' },
      { zh: '外星基地', en: 'alien outpost' },
    ],
    rare: [
      { zh: '全息投影', en: 'holographic projection' },
      { zh: '機械義肢', en: 'cybernetic limb' },
      { zh: '能量核心', en: 'glowing energy core' },
      { zh: '數據流特效', en: 'data stream effect' },
      { zh: '反重力碎片', en: 'anti-gravity debris' },
    ],
  },
  historical: {
    character: [
      { zh: '宮廷貴族', en: 'court noble' },
      { zh: '武士', en: 'samurai warrior' },
      { zh: '女偵探', en: 'vintage detective' },
      { zh: '航海船長', en: 'age-of-sail captain' },
      { zh: '古典學者', en: 'classical scholar' },
    ],
    pose: [
      { zh: '持扇掩面', en: 'fan-cover pose' },
      { zh: '持刀站姿', en: 'katana-ready stance' },
      { zh: '閱讀信件', en: 'reading a letter' },
      { zh: '敬禮', en: 'formal salute' },
      { zh: '端杯凝視', en: 'goblet-holding pose' },
    ],
    outfit: [
      { zh: '古典禮服', en: 'period formal dress' },
      { zh: '和風武士服', en: 'samurai attire' },
      { zh: '維多利亞風套裝', en: 'victorian suit' },
      { zh: '刺繡長袍', en: 'embroidered robe' },
      { zh: '宮廷軍裝', en: 'ceremonial uniform' },
    ],
    env: [
      { zh: '古城街道', en: 'old town street' },
      { zh: '宮殿長廊', en: 'palace corridor' },
      { zh: '茶館庭園', en: 'tea garden courtyard' },
      { zh: '歌劇院', en: 'grand opera hall' },
      { zh: '古堡書房', en: 'castle study room' },
    ],
    rare: [
      { zh: '古董懷錶', en: 'antique pocket watch' },
      { zh: '復古底片質感', en: 'vintage film texture' },
      { zh: '手寫墨跡', en: 'calligraphy ink effect' },
      { zh: '燭光煙霧', en: 'candle smoke glow' },
      { zh: '金邊刺繡細節', en: 'golden embroidery details' },
    ],
  },
  horror: {
    character: [
      { zh: '幽影使者', en: 'shadow stalker' },
      { zh: '詛咒人偶師', en: 'cursed puppeteer' },
      { zh: '黑夜獵手', en: 'night hunter' },
      { zh: '異界祭司', en: 'eldritch priest' },
      { zh: '廢墟倖存者', en: 'ruin survivor' },
    ],
    pose: [
      { zh: '緩慢回頭', en: 'slow turning-back pose' },
      { zh: '俯身潛伏', en: 'crouched lurking pose' },
      { zh: '伸手逼近', en: 'reaching-forward pose' },
      { zh: '牆角凝視', en: 'corner stare pose' },
      { zh: '奔跑逃離', en: 'running-away pose' },
    ],
    outfit: [
      { zh: '破舊長袍', en: 'tattered robe' },
      { zh: '暗色風衣', en: 'dark trench coat' },
      { zh: '詭異制服', en: 'eerie uniform' },
      { zh: '儀式袍', en: 'ritual outfit' },
      { zh: '血痕繃帶', en: 'blood-stained bandages' },
    ],
    env: [
      { zh: '廢棄醫院', en: 'abandoned hospital' },
      { zh: '霧夜森林', en: 'foggy night forest' },
      { zh: '地下室走廊', en: 'basement corridor' },
      { zh: '破敗劇院', en: 'derelict theatre' },
      { zh: '詛咒宅邸', en: 'haunted manor' },
    ],
    rare: [
      { zh: '紅光眼神', en: 'red glowing eyes' },
      { zh: '影子觸手', en: 'shadow tendrils' },
      { zh: '霧氣環繞', en: 'mist aura' },
      { zh: '裂紋特效', en: 'cracked distortion effect' },
      { zh: '恐怖粒子感', en: 'horror particle effect' },
    ],
  },
  oriental: {
    character: [
      { zh: '劍仙', en: 'sword immortal' },
      { zh: '狐妖', en: 'fox spirit' },
      { zh: '陰陽師', en: 'onmyoji master' },
      { zh: '龍宮公主', en: 'dragon palace princess' },
      { zh: '古風俠客', en: 'wuxia hero' },
    ],
    pose: [
      { zh: '御劍飛行', en: 'sword-riding pose' },
      { zh: '持傘漫步', en: 'walking with oil-paper umbrella' },
      { zh: '撫琴', en: 'playing guqin' },
      { zh: '掐訣施法', en: 'hand-seal casting pose' },
      { zh: '回眸含笑', en: 'gentle turning-back smile' },
    ],
    outfit: [
      { zh: '漢服', en: 'hanfu outfit' },
      { zh: '仙俠長袍', en: 'xianxia robe' },
      { zh: '和風和服', en: 'kimono style' },
      { zh: '華麗宮裝', en: 'imperial palace attire' },
      { zh: '武俠勁裝', en: 'wuxia combat outfit' },
    ],
    env: [
      { zh: '竹林', en: 'bamboo forest' },
      { zh: '雲海山巔', en: 'mountain above cloud sea' },
      { zh: '古風庭院', en: 'classical courtyard' },
      { zh: '燈火古城', en: 'lantern-lit ancient city' },
      { zh: '桃花谷', en: 'peach blossom valley' },
    ],
    rare: [
      { zh: '符咒光效', en: 'talisman glow effect' },
      { zh: '飛舞花瓣', en: 'falling petals effect' },
      { zh: '靈氣光環', en: 'spiritual aura' },
      { zh: '墨韻特效', en: 'ink wash effect' },
      { zh: '祥雲環繞', en: 'auspicious cloud aura' },
    ],
  },
};

export const CHARACTER_DEFAULT_STATE = {
  character: '',
  pose: '',
  outfit: '',
  env: '',
  color: '',
  shot: '',
  style: '',
  light: '',
  rare: '',
  negative: '',
};
